In [1]:
import pandas as pd

In [27]:
okhla_c1 = pd.read_csv('okhla_marked_c1.csv')
okhla_c2 = pd.read_csv('okhla_marked_c2.csv')
okhla_c3 = pd.read_csv('okhla_marked_c3.csv')
okhla_c4 = pd.read_csv('okhla_marked_c4.csv')

In [19]:
print(list(okhla_c1.columns))
print(list(okhla_c2.columns))
print(list(okhla_c3.columns))
print(list(okhla_c4.columns))

['From Date', 'To Date', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx']
['From Date', 'To Date', 'NH3', 'SO2', 'CO', 'Ozone', 'Benzene']
['From Date', 'To Date', 'Toluene', 'Temp', 'RH', 'WS', 'WD']
['From Date', 'To Date', 'SR', 'BP', 'AT', 'RF', 'TOT-RF']

In [21]:
columns= list(okhla_c1.columns)+list(okhla_c2.columns)+list(okhla_c3.columns)+list(okhla_c4.columns)
columns.remove("To Date")
columns.remove("From Date")

In [48]:
def clean(df):
    cols = list(df.columns)
    cols.remove("To Date")
    cols.remove("From Date")
    print(len(df),cols)
    for c in cols:
        df[c] = pd.to_numeric(df[c], errors='coerce')
    print(df)
    df = df.dropna()
    print(len(df))
    return df

df = clean(oklha_m3)
df.to_csv("okhla_static.csv")

8659 ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'SO2', 'CO', 'Ozone', 'Benzene', 'Toluene', 'RH', 'WS', 'WD', 'SR', 'BP', 'AT', 'RF', 'TOT-RF']
             From Date           To Date  PM2.5   PM10     NO    NO2    NOx  \
0     01-09-2021 00:00  01-09-2021 00:30   28.0   56.0  19.65  45.80  40.40
1     01-09-2021 00:30  01-09-2021 01:00   25.0   51.5  12.25  37.65  29.95
2     01-09-2021 01:00  01-09-2021 01:30   22.0   47.0   9.90  40.70  29.70
3     01-09-2021 01:30  01-09-2021 02:00   20.0   35.0   8.20  34.05  24.85
4     01-09-2021 02:00  01-09-2021 02:30   18.0   23.0   4.50  34.65  22.10
...                ...               ...    ...    ...    ...    ...    ...
8654  28-02-2022 07:00  28-02-2022 07:30   56.0  117.0  45.60  60.15  69.20
8655  28-02-2022 07:30  28-02-2022 08:00   50.0  120.5  43.05  64.75  69.45
8656  28-02-2022 08:00  28-02-2022 08:30   44.0  124.0  40.90  66.10  68.35
8657  28-02-2022 08:30  28-02-2022 09:00   44.5  128.0  39.40  70.05  69.40
8658  28-02-2022 09:00  28-02-2022 09:29   45.0  132.0  30.20  68.95  61.30

        NH3   SO2    CO  ...  Benzene  Toluene     RH   WS      WD    SR  \
0     27.70  9.60  1.00  ...     2.25    38.30  78.05  0.3  319.85   4.1
1     27.10  9.20  0.90  ...     2.20    38.05  78.15  0.3  319.90   4.1
2     30.20  9.55  0.90  ...     2.00    39.05  78.35  0.3  319.90   4.1
3     28.90  9.40  0.55  ...     1.70    32.60  78.40  0.3  319.85   4.1
4     23.50  8.90  0.50  ...     1.60    30.70  78.25  0.3  319.90   4.1
...     ...   ...   ...  ...      ...      ...    ...  ...     ...   ...
8654  31.70  5.80  0.90  ...     2.30    16.05  72.90  0.7  106.45  12.1
8655  33.55  6.40  0.85  ...     2.55    18.05  70.55  1.3  170.10  21.7
8656  32.35  6.75  0.95  ...     2.55    20.20  66.75  1.4  168.55  30.7
8657  32.05  7.45  0.95  ...     2.65    22.80  63.05  1.7  168.80  43.0
8658  31.90  7.80  0.95  ...     2.65    22.70  58.40  2.5  186.70  50.6

          BP     AT   RF  TOT-RF
0     984.40  26.30  0.0     0.0
1     984.10  26.25  0.0     0.0
2     983.85  26.10  0.0     0.0
3     983.45  26.10  0.0     0.0
4     983.20  26.15  0.0     0.0
...      ...    ...  ...     ...
8654  992.50  13.30  0.0     0.0
8655  992.65  13.85  0.0     0.0
8656  993.05  14.80  0.0     0.0
8657  993.45  15.75  0.0     0.0
8658  993.65  17.10  0.0     0.0

[8659 rows x 21 columns]
7094

In [46]:
okhla_c1
oklha_m1 = pd.merge(okhla_c1, okhla_c2,  how='outer', on=['From Date','To Date'])
oklha_m2 = pd.merge(oklha_m1, okhla_c3,  how='outer', on=['From Date','To Date'])
oklha_m2 = oklha_m2.drop('Temp', axis=1)

oklha_m3 = pd.merge(oklha_m2, okhla_c4,  how='outer', on=['From Date','To Date'])
oklha_m3

,From Date,To Date,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,...,Benzene,Toluene,RH,WS,WD,SR,BP,AT,RF,TOT-RF
0,01-09-2021 00:00,01-09-2021 00:30,28.0,56.0,19.65,45.80,40.40,27.7,9.6,1,...,2.25,38.3,78.05,0.3,319.85,4.1,984.4,26.3,0,0.0
1,01-09-2021 00:30,01-09-2021 01:00,25.0,51.5,12.25,37.65,29.95,27.1,9.2,0.9,...,2.2,38.05,78.15,0.3,319.9,4.1,984.1,26.25,0,0.0
2,01-09-2021 01:00,01-09-2021 01:30,22.0,47.0,9.90,40.70,29.70,30.2,9.55,0.9,...,2,39.05,78.35,0.3,319.9,4.1,983.85,26.1,0,0.0
3,01-09-2021 01:30,01-09-2021 02:00,20.0,35.0,8.20,34.05,24.85,28.9,9.4,0.55,...,1.7,32.6,78.4,0.3,319.85,4.1,983.45,26.1,0,0.0
4,01-09-2021 02:00,01-09-2021 02:30,18.0,23.0,4.50,34.65,22.10,23.5,8.9,0.5,...,1.6,30.7,78.25,0.3,319.9,4.1,983.2,26.15,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8654,28-02-2022 07:00,28-02-2022 07:30,56.0,117.0,45.60,60.15,69.20,31.7,5.8,0.9,...,2.3,16.05,72.9,0.7,106.45,12.1,992.5,13.3,0,0.0
8655,28-02-2022 07:30,28-02-2022 08:00,50.0,120.5,43.05,64.75,69.45,33.55,6.4,0.85,...,2.55,18.05,70.55,1.3,170.1,21.7,992.65,13.85,0,0.0
8656,28-02-2022 08:00,28-02-2022 08:30,44.0,124.0,40.90,66.10,68.35,32.35,6.75,0.95,...,2.55,20.2,66.75,1.4,168.55,30.7,993.05,14.8,0,0.0
8657,28-02-2022 08:30,28-02-2022 09:00,44.5,128.0,39.40,70.05,69.40,32.05,7.45,0.95,...,2.65,22.8,63.05,1.7,168.8,43,993.45,15.75,0,0.0
8658,28-02-2022 09:00,28-02-2022 09:29,45.0,132.0,30.20,68.95,61.30,31.9,7.8,0.95,...,2.65,22.7,58.4,2.5,186.7,50.6,993.65,17.1,0,0.0